name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Gradle JVM Args
      run: |
        echo "GRADLE_OPTS=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> $GITHUB_ENV
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Install example dependencies
      run: |
        cd example
        flutter pub get
      
    - name: Build Android
      run: |
        cd example
        flutter build apk --release --dart-define=FLUTTER_KOTLIN_VERSION=2.1.0
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: example/build/app/outputs/flutter-apk/app-release.apk