name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Install example dependencies
      run: |
        cd example
        flutter pub get
      
    - name: Build iOS (No Code Sign)
      run: |
        cd example
        flutter build ios --release --no-codesign
        
    - name: Upload iOS build
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: example/build/ios/iphoneos