name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Install example dependencies
      run: |
        cd example
        flutter pub get
      
    - name: Install iOS pods
      run: |
        cd example/ios
        pod install --repo-update
        
    - name: Build iOS (No Code Sign)
      run: |
        cd example
        flutter build ios --release --no-codesign --verbose
        
    - name: Upload iOS build
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: example/build/ios/iphoneos